-- =============================================================================
-- HOUND DOG — dados-base: estágios, playbook de objeções, configuração.
-- Idempotente (upsert). A doutrina vem de arquivo versionado, citado em "fonte".
-- =============================================================================

insert into public.estagios (id, funil, nome, descricao, ordem, cor, tipo) values
  ('novo',        'prospeccao', 'Novo',             'Encontrado ou importado. Ainda não qualificado nem abordado.',                        10, '#4b93e6', 'aberto'),
  ('qualificado', 'prospeccao', 'Qualificado',      'Passou no ICP tríplice (fit, timing, capacidade). Pronto pra abordar com gancho verdadeiro.', 20, '#8b5cf6', 'aberto'),
  ('abordado',    'prospeccao', 'Abordado',         'Primeiro contato feito. Aguardar a resposta: mandar de novo antes é insistência.',   30, '#c084fc', 'aberto'),
  ('conversando', 'prospeccao', 'Conversando',      'Respondeu. Objetivo: entender a dor e marcar a reunião, não vender por mensagem.',   40, '#f4c430', 'aberto'),
  ('reuniao',     'prospeccao', 'Reunião marcada',  'R1 de diagnóstico agendada. Levar dossiê e prévia.',                                  50, '#ff8a3d', 'aberto'),
  ('proposta',    'prospeccao', 'Proposta',         'Valor apresentado na reunião, olhando pro cliente. Tirar o compromisso ali.',         60, '#22d3ee', 'aberto'),
  ('negociacao',  'prospeccao', 'Negociação',       'Sim verbal ou ajuste de condição. Falta a entrada cair.',                            70, '#fb923c', 'aberto'),
  ('ganho',       'prospeccao', 'Ganho',            'Fechado. Entrada paga ou compromisso confirmado. Vira carteira.',                    80, '#25d366', 'ganho'),
  ('followup',    'prospeccao', 'Follow-up frio',   'Esfriou, mas pode voltar. Reativar só com gancho novo, sem pressão.',                90, '#64748b', 'espera'),
  ('perdido',     'prospeccao', 'Perdido / não-fit','Não tem a dor ou recusou. Respeitar e sair com a porta aberta.',                    100, '#ef4444', 'perdido')
on conflict (id) do update set nome = excluded.nome, descricao = excluded.descricao, ordem = excluded.ordem,
  cor = excluded.cor, tipo = excluded.tipo, funil = excluded.funil;

insert into public.playbook_objecoes (id, rotulo, gatilhos, leitura, resposta, alternativas, evitar, fonte, ordem) values
('preco', 'Preço / "tá caro"',
  array['quanto custa','quanto fica','qual o valor','qual valor','valores','preço','preco','tá caro','ta caro','muito caro','orçamento','orcamento','não tenho dinheiro','nao tenho dinheiro','sem grana','investimento'],
  'Pergunta de preço por mensagem quase sempre é curiosidade ou valor percebido baixo. Preço solto no chat vira commodity: a meta aqui é agendar, não cotar.',
  'Ótima pergunta! A resposta honesta é: depende do que faz sentido pro seu caso. Por isso prefiro te mostrar as opções numa conversa rápida, com o valor no detalhe. Prefere amanhã de manhã ou à tarde?',
  array['Nem falei de preço ainda 🙂 e tem opção que cabe. Deixa eu te mostrar primeiro, aí você decide. Pode ser amanhã?',
        'Entendo. Deixa eu te perguntar: quantos clientes por mês você acha que te procuram e não te acham hoje? É isso que a gente resolve. Faz sentido eu te mostrar o quanto isso volta pra você antes de decidir se é caro?'],
  'Mandar valor por escrito, baixar preço no susto, desconto por pressa. Projeto acima de R$ 2.000 não fecha por WhatsApp.',
  'Horus-Comercial/50-precos.md · 60-quebra-objecao.md · _conhecimento/network/apresentacao-de-preco-e-objecao.md', 10),
('vou_pensar', '"Vou pensar"',
  array['vou pensar','vou ver','deixa eu ver','depois te falo','te retorno','vou analisar','preciso pensar','vou avaliar'],
  '"Vou pensar" é sinal, não é não. Isolar o que trava, sem pressionar.',
  'Claro, faz sentido pensar. Só pra eu te ajudar melhor: além de pensar, tem alguma parte específica que ficou com dúvida? Preço, prazo ou como funciona?',
  array['Tranquilo! Pra você pensar com tudo na mão: o que pesaria mais na decisão, o investimento ou o tempo de colocar no ar?'],
  'Cobrar prazo, criar urgência artificial.',
  '_memoria/comercial.md · Horus-Comercial/60-quebra-objecao.md', 20),
('socio', 'Sócio / cônjuge decide junto',
  array['sócio','socio','sócia','socia','minha esposa','meu marido','minha irmã','minha irma','meu irmão','meu irmao','ver com','falar com meu','decidir junto','meu pai','minha mãe','minha mae'],
  'Parte é cortina de fumaça, parte é verdade (e essa se respeita). Decisor ausente é a causa nº 1 do cliente que some depois do sim.',
  'Perfeito, e faz bem. Só pra vocês não recomeçarem do zero depois: que parte exatamente precisam alinhar? Se ajudar, marcamos 15 minutos com vocês dois e eu tiro as dúvidas direto.',
  array['Faz todo sentido. Quer que eu prepare um resumo de uma página pra vocês olharem juntos, e a gente fala 15 min depois?'],
  'Mandar proposta pro grupo e esperar. Vender pra quem não decide.',
  '_conhecimento/network/cobranca-e-protecao-comercial.md · _memoria/comercial.md', 30),
('ja_tem', 'Já tem alguém fazendo / já tem site',
  array['já tenho','ja tenho','já temos','ja temos','já tem alguém','ja tem alguem','equipe de marketing','sobrinho','meu filho faz','agência','agencia','já fiz site','ja fiz site','já estão fazendo','ja estao fazendo','temporariamente'],
  'Não brigar, ficar curioso. Site ou domínio fora do ar é prova de projeto travado. Se quem objeta é gatekeeper (não decide), a prévia fica no coldre.',
  'Que bom! Já está no ar e funcionando bem? E eles já integram o pedido ou agendamento no WhatsApp e a volta do cliente, ou é só a página por enquanto?',
  array['Que bom! Se um dia quiser uma segunda opinião sem compromisso, eu guardo seu contato.',
        'Show! Quando o site estiver no ar, qual o plano pra ele aparecer no Google da cidade?'],
  'Contestar, falar mal do outro, despejar a prévia em quem não decide.',
  '_conhecimento/network/objecao-ja-tem-alguem-fazendo.md · _conselho/logs/2026-09-15-mullsanni-gatekeeper.md', 40),
('instagram_basta', '"Faço tudo pelo Instagram"',
  array['pelo instagram','pelo insta','só instagram','so instagram','direct','rede social','funciona bem assim','já vendo bem','ja vendo bem','pelo zap'],
  'Mostrar o que o canal não cobre, sem desmerecer o que funciona. Se depois de duas perguntas não dói, é não-fit.',
  'Ótimo que funciona! E quando alguém te procura no Google em vez do Insta, o que aparece? Instagram é terreno alugado: se a conta cai, cai tudo. Vale 15 minutos pra eu te mostrar como os dois trabalham juntos?',
  array['Que bom que o Insta está rendendo! Só por curiosidade: quem pesquisa "[serviço] em [cidade]" no Google acha vocês?'],
  'Dizer que Instagram não serve. Vender "design".',
  '_memoria/comercial.md · Horus-Comercial/60-quebra-objecao.md', 50),
('sem_tempo', 'Sem tempo agora',
  array['sem tempo','correria','agora não dá','agora nao da','muito corrido','corrido','ocupado','ocupada','outra hora','semana que vem'],
  'Tempo é a moeda do dono de negócio pequeno. Oferecer pouco tempo com tudo pensado.',
  'Justamente por isso: a ideia é te tomar pouco tempo e te dar mais depois. São 20 minutos e eu chego com tudo pensado. Prefere começo da manhã ou fim da tarde?',
  array['Total. Deixa eu facilitar: te mando um áudio de 1 minuto e você ouve quando puder. Pode ser?'],
  'Mandar textão explicando tudo.',
  'Horus-Comercial/60-quebra-objecao.md', 60),
('por_escrito', '"Me manda por escrito"',
  array['manda por escrito','me manda','manda por aqui','manda proposta','manda o valor','manda os valores','manda por email','manda por e-mail','manda um pdf','manda o orçamento','manda o orcamento'],
  'Proposta em PDF ou no grupo é o vale frio: o cliente decide sozinho, sem ninguém pra dissolver a objeção.',
  'Mando um resumo sim! Mas o que faz diferença é eu te mostrar no teu caso específico, 10 minutinhos. No texto a gente perde metade. Topa amanhã?',
  array['Mando! E pra não virar mais um PDF perdido, que tal 10 minutos por vídeo pra eu te mostrar funcionando?'],
  'Mandar proposta pra decidir sozinho. Decidir por documento.',
  '_memoria/comercial.md (o padrão de perda de 06/09) · Horus-Comercial/60-quebra-objecao.md', 70),
('sem_interesse', 'Sem interesse',
  array['não tenho interesse','nao tenho interesse','sem interesse','não quero','nao quero','não preciso','nao preciso','dispenso','não obrigado','nao obrigado'],
  'Uma pergunta de dor antes de sair. Sem dor depois de duas perguntas = não-fit: respeitar e deixar a porta aberta.',
  'Entendo, sem problema! Só uma coisa: hoje vocês aparecem no Google quando alguém procura pelo serviço de vocês na cidade? Se um dia isso virar prioridade, é só me chamar.',
  array['Tranquilo, obrigado pela resposta! Fico à disposição se mudar algo.'],
  'Insistir, mandar de novo, argumentar.',
  'Horus-Comercial/60-quebra-objecao.md · 20-roteiro-ligacao.md', 80),
('desconfianca', 'Desconfiança / "é golpe?"',
  array['golpe','como conseguiu meu número','como conseguiu meu numero','quem é você','quem e voce','quem é vc','spam','confiável','confiavel','conheço vocês','conheco voces','de onde'],
  'Desconfiança é legítima. Responder com gancho verdadeiro e prova concreta, nunca pretexto inventado.',
  'Justo desconfiar, tem muita gente ruim nesse mercado. Achei vocês pesquisando negócios da região e cheguei com algo concreto sobre o seu negócio, sem pedir nada pra você ver. Posso te mostrar em 10 minutos, por vídeo ou aí pessoalmente?',
  array['Faz sentido perguntar! Sou da Hórus, aqui de Salvador. Te mando nosso Instagram pra você conhecer antes de qualquer conversa.'],
  'Pretexto falso ("falei com um funcionário seu"), pressão.',
  '_memoria/comercial.md (gancho verdadeiro) · _conhecimento/network/abordagem-e-prospeccao.md', 90),
('nao_e_comigo', 'Não é com essa pessoa (gatekeeper)',
  array['não sou o dono','nao sou o dono','não sou eu','nao sou eu','o responsável','o responsavel','o dono','a dona','gerente','não decido','nao decido','secretária','secretaria','atendente','vou repassar'],
  'Não vender pra quem não decide. Buscar a ponte até o decisor, com calor e sem pressão.',
  'Entendi, obrigado! Com quem eu falo sobre a presença de vocês no Google, e qual o melhor horário pra pegar essa pessoa?',
  array['Perfeito, obrigado por repassar! Se puder me dizer o nome de quem cuida disso, falo direto e não te tomo mais tempo.'],
  'Despejar prévia ou preço no gatekeeper.',
  'Horus-Comercial/20-roteiro-ligacao.md · _conselho/logs/2026-09-15-mullsanni-gatekeeper.md', 100),
('ja_tentei', 'Já tentei e não deu certo',
  array['já tentei','ja tentei','não deu certo','nao deu certo','já tive site','ja tive site','gastei dinheiro','sumiu','me enrolaram','não funcionou','nao funcionou'],
  'Experiência ruim anterior: ouvir primeiro, depois mostrar o processo em fases (valor provado antes de seguir).',
  'Poxa, entendo o pé atrás. O que deu errado da outra vez? Pergunto porque é justamente o que a gente evita: trabalho em fases, você vê funcionando antes de seguir pro próximo passo.',
  array['Faz sentido estar com o pé atrás. O que você precisaria ver pra confiar de novo?'],
  'Prometer resultado. Falar mal de quem fez antes.',
  '_memoria/comercial.md (oferta em fases)', 110),
('momento', 'Momento ruim / caixa apertado',
  array['momento difícil','momento dificil','crise','movimento fraco','fim do ano','ano que vem','mês que vem','mes que vem','depois do carnaval','sem caixa','apertado','devagar'],
  'Se a trava é caixa, facilitar a condição (fase menor, cartão parcelado), nunca baixar o valor do trabalho.',
  'Faz sentido olhar pro caixa. E justamente em mês mais fraco, quem aparece no Google pega o cliente que ainda está procurando. Posso te mostrar uma primeira fase enxuta, e se não fizer sentido agora você decide com calma?',
  array['Entendo. Se ajudar, dá pra começar pela fase mais enxuta e parcelar no cartão. Vale eu te mostrar?'],
  'Desconto relâmpago. Pressão de escassez (e em setor regulado, nunca).',
  '_conhecimento/network/apresentacao-de-preco-e-objecao.md · cobranca-e-protecao-comercial.md', 120)
on conflict (id) do update set rotulo = excluded.rotulo, gatilhos = excluded.gatilhos, leitura = excluded.leitura,
  resposta = excluded.resposta, alternativas = excluded.alternativas, evitar = excluded.evitar,
  fonte = excluded.fonte, ordem = excluded.ordem;

insert into public.config (chave, valor) values
  ('instagram', '{"handle":"horuspublicidade","intervalo_horas":6}'),
  ('claude', '{"modelo_chat":"opus","modelo_analise":"sonnet","modelo_pesquisa":"opus"}'),
  ('whatsapp', '{"ativo":false,"auto_analisar":"leads","briefing_diario":true,"briefing_hora":"08:00","lembretes":true,"limite_hora":30}'),
  ('metas', '{"abordagens_semana":5,"reunioes_mes":2,"referencia":"Teste de 90 dias, mês 1 (_gestao/teste-90-dias.md). Benchmark do network no modelo focado: 3 a 7 abordagens de qualidade por dia (referência, não meta)."}'),
  ('score', '{"sem_site":30,"instagram_movimento":20,"dono_acessivel":15,"gmb_fraco":15,"nicho_conhecido":10,"timing":10,"fonte":"Horus-Comercial/30-checklist-qualificacao.md"}'),
  ('nichos_conhecidos', '["floricultura","flores","café","cafe","psicologia","psicólogo","estética","estetica","odontologia","dentista","oficina","automotiv","fitness","academia","pilates","estúdio","massoterapia","doceria","confeitaria","arquitetura","interiores","clínica","clinica"]'),
  ('praca', '{"cidade":"Salvador","uf":"BA","regiao":["Salvador","Lauro de Freitas","Camaçari","Simões Filho","Candeias","Dias d''Ávila"]}')
on conflict (chave) do nothing;

insert into public.farejador_status (id, whatsapp_status) values ('principal', 'desligado')
on conflict (id) do nothing;
